[IV 21-22] Objetivo2
lentes4k/cAppjon pull request #15
Opened 2021-10-08 11:05 UTC by Paszser

Cuando se haga merge del PR tras su aprobación, se cerrarán los issues #17 #18 #19 y #20. 
closes #17
closes #18 
closes #19 
closes #20 

Avanza tanto #6 y #5 como [M1](https://github.com/lentes4k/Proyecto-IV/milestone/1) para continuar con su posterior desarrollo.

2021-10-11 14:29 UTC, lentes4k commented
Por mi parte lo veo correcto, se crean las clases que necesitan. Ya puede echarle un ojo @jj

2021-10-11 16:08 UTC, JJ commented on iv.yaml
> +entidad: src/nota.py
Sólo hay que poner esto una vez.

2021-10-12 16:28 UTC, JJ requested changes
Vale que antes del comentario pongáis "update" esto y lo otro. Pero tanto en clase como en el comentario os debería quedar muy claro que los commits se hacen con un mensaje de commit claro, y que se refiera a un issue determinado. Un mensaje "update loquesea" es totalmente ínútil, y no ayuda absolutamente nada porque no se sabe sobre qué issue trabaja. Por otro lado, os recuerdo que al aceptar el PR se tienen que cerrar los issues correspondientes, para lo que tendréis que poner el mensaje para que así suceda.

2021-10-12 16:28 UTC, JJ commented on iv.yaml
> +entidad:
El guión os dice claramente que incluyáis solo uno. Esto va a dar error en todos los objetivos siguientes. Por favor, tratad de seguir el guión, porque es la especificación para los tests automáticos.

2021-10-12 16:28 UTC, JJ commented on src/cajon.py
> +    nombre = '' #Nombre del Cajón
Si vais a incluir documentación, no lo hagáis como comentarios, sino siguiendo las buenas prácticas de documentación de Python. Por favor, consultadlas y usadlas.

2021-10-14 07:03 UTC, lentes4k commented
Está ya para aceptar y mergear @JJ?

2021-10-15 05:10 UTC, JJ requested changes
Para que un producto sea mínimamente *viable* se tiene que comprobar que funciona; en este caso, que compila. ¿Alguno lo habéis comprobado?

2021-10-15 05:10 UTC, JJ commented on src/nota.py
> +class Nota:
¿has compilado esto?

2021-10-16 07:40 UTC, JJ commented on src/nota.py
> +    #def clasificarNota(contenido):
No es una buena práctica comentar código.

2021-10-16 08:49 UTC, JJ commented
> > Si metéis dos clases en el M1, ya no es mínimamente viable. Deberíais haber metido uno solo. Por favor, documentaros bien sobre lo que es una dataclass, que sirve para dos cosas: anotaciones de tipo (que no estáis usando) y generar automáticamente el **init** (que no sólo no estáis usando, sino que estáis creando un método que no sirve para nada). El tipo de cada uno de los atributos tendréis que discutirlo en un issue, así como cualquier comprobación adicional que queráis hacer. Además, estáis poniendo en la nota el cajón en el que está y en cada cajón todas las notas que tiene. No parece que tenga mucho sentido. Aparte, no hay ninguna historia de usuario que realmente se refiera a la lógica de negocio, que es lo esencial. La creación de reglas "inteligente" para dirigir nota a un cajón (¿o a varios cajones?) debería estar tanto en una historia de usuario como en un hito. Recuerda que lo esencial es la lógica de negocio.
> 
> Vale, viendo esto creo que deberíamos de dejar solamente la clase nota. Añadido a esto creo que la clase nota debería de tener dos atributos:
> 
>     * Texto: que contendrá el texto de la nota
> 
>     * Palabras clave, una suerte de array de palabras que más adelante el programa se encargará de extraer (o el programador inclurá) para proceder con la clasificación.
> 
> 
> Además se crearán dos accesores para cada uno de los atributos, así como un constructor que creará el array de palabras vacío y guardará en texto la nota que se le pasará al constructor. En ese caso se podrá borrar la clase cajón que será creada y utilizada en un futuro. Si todo te parece bien procede con esa serie de cambios @Paszser

Por favor, aclarad eso en un issue.

2021-10-16 11:36 UTC, Paszser commented
Cambios realizados tras los issues discutidos. Procedo a que mi product manager @lentes4k  lo revise ⏳ .

2021-10-16 12:13 UTC, lentes4k commented
Estimo que se adapta a las últimas decisiones que he tomado respecto a los comentarios de @JJ. 
Cuando pueda que él mismo le eche un vistazo para cercionarnos de esto

2021-10-16 12:13 UTC, lentes4k approved these changes

2021-10-17 06:52 UTC, JJ approved these changes
Creo que ya se ha conseguido el PMV, pero
1. Habéis dejado en el cuerpo del PR el cierre de issues que ya no estáis tratando. Mucho cuidado con eso.
2. Por favor, mirad dónde se ponen los docstrings y corregidlo antes de mergearlo.

2021-10-18 14:17 UTC, merged