[IV-21-22] Creación de la imagen Dockerfile y la GitHub Action
lentes4k/cAppjon pull request #28
Opened 2021-11-19 16:11 UTC by lentes4k

2021-11-19 16:15 UTC, lentes4k commented
@JJ listo para revisión

2021-11-20 13:04 UTC, JJ requested changes
No sé muy bien como funciona esto, porque al Dockerfile le falta todavía una vuelta o dos... Por lo demás, el issue está en un milestone y demás, así que bien.

2021-11-20 13:04 UTC, JJ commented on .github/workflows/docker-publish.yml
> +      - 'pyrpoject.toml'
typo

2021-11-20 13:04 UTC, JJ commented on Dockerfile
> +FROM python:3.10-alpine
Tienes que documentar la elección de esta imagen base.

2021-11-20 13:04 UTC, JJ commented on Dockerfile
> +RUN  pip3 install poetry
¿No se instala ninguna dependencia más? ¿Seguro?

2021-11-22 15:05 UTC, lentes4k commented
> No sé muy bien como funciona esto, porque al Dockerfile le falta todavía una vuelta o dos... Por lo demás, el issue está en un milestone y demás, así que bien.

Las vueltas que le faltan son las cosas que me comentas más abajo? Lo de documentar mis elecciones? O que hay algo mal en el Dockerfile?

2021-11-22 15:06 UTC, lentes4k commented on Dockerfile
> +RUN  pip3 install poetry
En teoria instala y funciona por lo que no he echado en falta ninguna dependecia más ni se queja el contenedor al lanzarlo

2021-11-22 16:43 UTC, JJ commented
> > No sé muy bien como funciona esto, porque al Dockerfile le falta todavía una vuelta o dos... Por lo demás, el issue está en un milestone y demás, así que bien.
> 
> Las vueltas que le faltan son las cosas que me comentas más abajo? Lo de documentar mis elecciones? O que hay algo mal en el Dockerfile?

Todo ello, en general. Para eso lo comento.

2021-11-22 18:19 UTC, lentes4k commented
He añadido una pequeña documentación y arreglado el typo, si me falta algo y me puedes dar alguna pista... :smile:

2021-11-22 18:57 UTC, JJ requested changes
A ver si lo comentado te da alguna pista.

2021-11-22 18:57 UTC, JJ commented on Dockerfile
> +RUN  pip3 install poetry
Vamos a ver, en el contenedor tienes que instalar las dependencias que necesite para pasar los tests. Creo que poetry instala lo que no encuentra, pero de lo que se trata es que esté ya instalado. ¿No hará falta instalar alguna dependencia para, no sé, hacer tests?

2021-11-22 18:57 UTC, JJ commented on docs/docker_doc.md
> +En este caso he optado por elegir el contenedor oficial de `Python` en su versión `alpine` ya que prescinde de muchas librerias innecesarias y ahorramos memoria buscando la livianidad del contenedor.
Tendrías que justificarlo un poco más; versión, tipo de contenedor, todo eso.

2021-11-24 15:46 UTC, lentes4k commented
@JJ listo!, a ver que tal :smile:

2021-11-26 08:01 UTC, JJ approved these changes
La justificación no está del todo hecha como hablamos ayer el clase, pero el resto me vale.

2021-11-26 11:41 UTC, merged