[IV-21-22] Objetivo 6
lentes4k/cAppjon pull request #31
Opened 2021-12-03 12:11 UTC by lentes4k

* [ ]  ¿Se han configurado varios sistemas de integración continua?
* [ ]  ¿Se ha configurado correctamente el *Checks API* en los sistemas en los que
   sea necesario para que aparezca correctamente en GitHub (y se pueda comprobar
   desde los tests)?
* [ ]  ¿Uno de los sistemas configurados permite comprobar cuales son las versiones
   del lenguaje con las que funciona correctamente nuestra aplicación?
* [ ]  ¿Se escogen de forma adecuada las versiones del lenguaje que se testean,
   tanto en el sistema de CI como en el contenedor Docker?

2021-12-03 12:18 UTC, lentes4k commented
pronto para revisão @JJ

2021-12-07 19:26 UTC, JJ requested changes
El PMV no está suficientemente bien definido (incluyendo "ejemplos") y tampoco menciona por ningún lado lo que se está haciendo en este objetivo.

2021-12-08 09:48 UTC, lentes4k commented
He añadido documentación y editado el cuerpo del PR para acceder de manera fácil a las issues relacionadas y a la documentación, ya me vas contando @JJ

2021-12-08 12:47 UTC, JJ approved these changes
Has puesto literalmente los dos sistemas de CI que hemos mencionado en clase. Ni siquiera has intentado mirar otros, ni seleccionarlos en base a algún criterio.
Como ya los has elegido, es tontería que te pida cambiarlos. Más trabajo para mi, y más trabajo para ti para buscar qué poner para justificar una decisión que ya has tomado. Así que por lo menos busca un poco las opciones de CI/CD que hay y mira a ver si alguna te podría haber convenido un poco más.

2021-12-08 13:34 UTC, lentes4k commented
> Has puesto literalmente los dos sistemas de CI que hemos mencionado en clase. Ni siquiera has intentado mirar otros, ni seleccionarlos en base a algún criterio.
> 
> Como ya los has elegido, es tontería que te pida cambiarlos. Más trabajo para mi, y más trabajo para ti para buscar qué poner para justificar una decisión que ya has tomado. Así que por lo menos busca un poco las opciones de CI/CD que hay y mira a ver si alguna te podría haber convenido un poco más.

Si, desconocía el tema de integración continua y comencé mirando los hablados en clase.
Me lancé con CircleCI y probé con él a hacer el testeo de versiones pero tras las complicaciones que me encontraba pasé.
Me documenté y vi que con Travis era súper sencillo y me registré para ver cómo iba pero al pedir la tarjeta pues pasé también. 
Ya después de eso me documenté con las GH Actions y lo entendí bien y me puse hacerlo.
Aún así es cierto que podría haber barajado otras opciones pero al final fui esclavo del dicho "más vale lo malo conocido que lo bueno por conocer"

2021-12-09 07:47 UTC, merged