[IV-21-22] Objetivo 7
lentes4k/cAppjon pull request #34
Opened 2021-12-17 11:50 UTC by lentes4k

2021-12-17 11:56 UTC, lentes4k commented
os toca trabajito @modejota @Slowmybrosh seguramente me saquéis mil errores porque ni yo se muy bien lo que he hecho (es mi primera vez haciendo logging :cry:

2021-12-18 09:28 UTC, modejota commented on cappjon/manejador.py
> +			logging.error('Error creando la nota')
En un manejador no puedes lanzar una excepción así porque sí, por el API que tendremos que montar en objetivos siguientes. Tiene que ser algo que se pueda traducir a estados de HTTP.

2021-12-18 09:44 UTC, Slowmybrosh commented on docs/logging.md
> +### Elección de la herramienta de logging
Quizás la justificación se quede un poco corta, a lo mejor sería conveniente explorar otras opciones además de la que se comentó en clase. Simplemente por comprobar si otras herramientas se ajustan mejor al proyecto o no

2021-12-18 09:44 UTC, Slowmybrosh commented on docs/logging.md
> +
Quizás la justificación se quede un poco corta, a lo mejor sería conveniente explorar otras opciones además de la que se comentó en clase. Simplemente por comprobar si otras herramientas se ajustan mejor al proyecto o no

2021-12-18 09:48 UTC, Slowmybrosh commented on cappjon/config.py
> +
La clase de configuración parece que está bien hecha y has entendido el concepto de abstraer la configuración para que sea posible estructurar de manera automática los ajustes.

2021-12-18 19:28 UTC, lentes4k commented on cappjon/manejador.py
> +			logging.error('Error creando la nota')
bastaría con devolver un 404 al logging y el mensaje en texto ponerlo de otra forma?

2021-12-18 19:28 UTC, lentes4k commented on docs/logging.md
> +
Okey, estoy mirando más alternativas para completar la documentación

2021-12-18 19:57 UTC, modejota commented on cappjon/manejador.py
> +			logging.error('Error creando la nota')
Con el código actual, solo puedes tener una nota, por lo que la clase manejadora realmente no está manejando nada desde ese punto de vista, no sé si me explico. 
Entiendo que querrás mantener varias notas, por lo que tendrás que tener alguna estructura de datos que las almacene e identifique de manera unívoca. Las excepciones que podría lanzar ese manejador serían, por ejemplo, "ID no existente" (que la API capturaría y provocaría que se devolviera al cliente un 404)

2021-12-19 10:46 UTC, lentes4k commented on cappjon/manejador.py
> +			logging.error('Error creando la nota')
Si no he entendido mal tu comentario creo que debría de haber obtenido una funcionalidad parecida a lo que dices

2021-12-19 11:13 UTC, modejota commented on cappjon/cappjon.py
> +class Cappjon:
Así, tiene un nombre e ID el cajón entero, pero no cada nota. Sigues sin poder acceder a cada nota de forma unívoca (salvo quizás por la posición, pero tendrás problemas cuando borres notas)

2021-12-19 11:17 UTC, lentes4k commented on docs/logging.md
> +
listo @Slowmybrosh he explorado otras dos opciones que podrían ser útiles en mi proyeco y justificado su no elección

2021-12-19 11:44 UTC, lentes4k commented on cappjon/cappjon.py
> +class Cappjon:
listo!

2021-12-22 06:46 UTC, JJ requested changes
Estaría bien si usaras el log en algún sitio... El problema es que no lo usas.

2021-12-22 06:46 UTC, JJ commented on test/test_manejador.py
> +	def crea_notas(manejador):
Deberías testear también las posibles excepciones.

2021-12-22 07:59 UTC, lentes4k commented
> Estaría bien si usaras el log en algún sitio... El problema es que no lo usas.

En este punto tuve bastantes dudas. Todos los sitios en los que me documenté hablablan principlamente de la clase manejadora y el logging, pero no encontré nada de como usarlo realmente. Así que si me puedes dar una pistilla @JJ ... 😧

2021-12-22 08:59 UTC, JJ commented
> > Estaría bien si usaras el log en algún sitio... El problema es que no lo usas.
> 
> En este punto tuve bastantes dudas. Todos los sitios en los que me documenté hablablan principlamente de la clase manejadora y el logging, pero no encontré nada de como usarlo realmente. Así que si me puedes dar una pistilla @JJ ... anguished

Hombre, tienes que hacer logs de todos los eventos que sucedan... O al menos usarlo en algún sitio. Simplemente crea un objeto log, pásaselo al constructor de la clase manejadora, y loguea cuando hagas cosas ahí.

2021-12-22 19:23 UTC, lentes4k commented
Si no me equivoco creo que he hecho los cambios que me has comentado @JJ

2021-12-23 11:36 UTC, JJ requested changes
Todavía no está demasiado lograda la integración de los logs. Aparte de que lo usas una sola vez, y la clase manejador es un poco escasa...

2021-12-23 11:36 UTC, JJ commented on cappjon/manejador.py
> +	def crea_nota(self, texto):
ESto va a ser bastante insuficiente en los siguientes objetivos...

2021-12-23 11:36 UTC, JJ commented on cappjon/logger.py
> +	def logging(self):
Esto no sé muy bien lo que hace. No hace log, sino que configura el log. Tienes que crear una clase de logging cuyos objetos tengan métodos para logear en los diferentes niveles que comentamos en clase.

2021-12-27 10:06 UTC, lentes4k commented
Creo que ya he mejorado lo que me has comentado @JJ

2021-12-30 08:39 UTC, lentes4k commented
Resuelta #35 debería de estar todo ya @JJ  :santa: :santa: :santa:

2021-12-30 19:14 UTC, JJ approved these changes
:+1:

2022-01-02 09:20 UTC, merged